# Generated by Django 3.1.7 on 2021-04-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listrequests', '0002_charity_request_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_details', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
                ('created_by', models.IntegerField(default=None)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listrequests.charity_request')),
            ],
        ),
    ]
