# Generated by Django 3.1.7 on 2021-04-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='beneficiaries',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
