# Generated by Django 3.1.7 on 2021-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('constitution_doc', models.FileField(upload_to='uploads/')),
                ('deeds_document', models.FileField(upload_to='uploads/')),
                ('elligibility_doc', models.FileField(upload_to='uploads/')),
                ('charity_type', models.CharField(blank=True, choices=[('', '------------'), ('educational', 'Educational'), ('health', 'Healthy'), ('environment', 'Environment'), ('international', 'International')], default='no', max_length=100)),
                ('approved', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
                ('created_by', models.IntegerField(default=None)),
            ],
        ),
    ]
