# Generated by Django 3.1.7 on 2021-04-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity_request',
            name='password',
            field=models.CharField(default='qwertypass', max_length=11),
        ),
    ]
