# Generated by Django 3.1.7 on 2021-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listrequests', '0003_remove_charity_request_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity_Request_Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('approved', models.IntegerField(default=0)),
                ('password', models.CharField(default='qwertypass', max_length=11)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
    ]
